{{- if (and .Values.installCRDs (not (.Capabilities.APIVersions.Has "mysql.presslabs.org/v1alpha1"))) }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: '{{ template "mysql-operator.name" . }}'
    chart: '{{ template "mysql-operator.chart" . }}'
    controller-tools.k8s.io: "1.0"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: mysqlbackups.mysql.presslabs.org
  annotations:
    helm.sh/hook: crd-install
spec:
  group: mysql.presslabs.org
  names:
    kind: MysqlBackup
    plural: mysqlbackups
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: '{{ template "mysql-operator.name" . }}'
    chart: '{{ template "mysql-operator.chart" . }}'
    controller-tools.k8s.io: "1.0"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: mysqlclusters.mysql.presslabs.org
  annotations:
    helm.sh/hook: crd-install
spec:
  group: mysql.presslabs.org
  names:
    kind: MysqlCluster
    plural: mysqlclusters
    shortNames:
    - mysql
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.readyNodes
    status: {}
  version: v1alpha1
{{- end }}
