{{- if and .Values.podSecurityPolicy.enabled .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mysql-operator
roleRef:
  kind: Role
  name: mysql-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts:
- kind: ServiceAccount
  name: {{ template "mysql-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
