apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
      role: controller
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        role: controller
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | indent 8 | printf "\n%s" }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | indent 8 | printf "\n%s" }}
      {{- end }}
      containers:
        - name: titanium
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            {{- if .Values.orc.enabled }}
            - --orchestrator-uri=http://{{ .Release.Name }}-orc/
            - --orchestrator-secret={{ .Release.Name }}-topology-secret
            {{- end }}
            {{- range $key, $value := .Values.conf }}
            - --{{ $key }}={{ $value }}
            {{- end }}

      
