workspace:
  base: /go
  path: src/github.com/presslabs/titanium

pipeline:
  build-operator:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - make
      - make test

  publish-operator:
    group: publish
    image: plugins/docker
    mirror: https://mirror.gcr.io
    registry: gcr.io
    repo: gcr.io/pl-infra/titanium-operator
    username: _json_key
    tags: ["${DRONE_BRANCH/master/latest}", "${DRONE_COMMIT_SHA:0:7}"]
    force_tag: true
    build_args:
      - release="${DRONE_COMMIT_SHA:0:7}"
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: DOCKER_PASSWORD
    when:
      event: push

  publish-toolbox:
    group: publish
    image: plugins/docker
    mirror: https://mirror.gcr.io
    registry: gcr.io
    repo: gcr.io/pl-infra/titanium-toolbox
    dockerfile: hack/docker/toolbox/Dockerfile
    username: _json_key
    tags: ["${DRONE_BRANCH/master/latest}", "${DRONE_COMMIT_SHA:0:7}"]
    force_tag: true
    build_args:
      - release="${DRONE_COMMIT_SHA:0:7}"
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: DOCKER_PASSWORD
    when:
      event: push

  e2e-tests:
    image: gcr.io/pl-infra/kluster-toolbox:latest
    pull: true
    secrets:
      - GOOGLE_CREDENTIALS
      - GOOGLE_PROJECT_ID
      - TITANIUM_TEST_GS_CREDENTIALS
    environment:
      - TITANIUM_IMAGE_TAG=${DRONE_COMMIT_SHA:0:7}
      - OPERATOR_IMAGE=gcr.io/pl-infra/titanium-operator:${DRONE_COMMIT_SHA:0:7}
      - KUBECONFIG=/go/.kube/config
    commands:
      - sleep 1

services:
  minikube:
    image: gcr.io/pl-infra/drone-minikube:v1.9.0
    privileged: true
    secrets:
      - GOOGLE_CREDENTIALS

