workspace:
  base: /go
  path: src/github.com/presslabs/mysql-operator

pipeline:
  build:
    image: golang:1.9
    group: build
    environment:
      - APP_VERSION=${DRONE_BRANCH/master/latest}
    commands:
      - make full-test
      - make build
      - make install-docker
    when:
      event: push

  build:
    image: golang:1.9
    group: build
    environment:
      - APP_VERSION=${DRONE_BRANCH/master/latest}
    commands:
      - make full-test
    when:
      event: pull_request

  build:
    image: golang:1.9
    group: build
    environment:
      - APP_VERSION=${DRONE_TAG}
    commands:
      - make full-test
      - make build
      - make install-docker
    when:
      event: tag

  publish-operator:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/mysql-operator
    username: presslabs+drone
    dockerfile: hack/docker/mysql-operator/Dockerfile
    context: hack/docker/mysql-operator
    tags: ["${DRONE_BRANCH/master/latest}"]
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: push

  publish-operator:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/mysql-operator
    username: presslabs+drone
    dockerfile: hack/docker/mysql-operator/Dockerfile
    context: hack/docker/mysql-operator
    tags: ["${DRONE_TAG}"]
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: tag

  publish-helper:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/mysql-helper
    username: presslabs+drone
    dockerfile: hack/docker/mysql-helper/Dockerfile
    context: hack/docker/mysql-helper
    tags: ["${DRONE_BRANCH/master/latest}"]
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: push

  publish-helper:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/mysql-helper
    username: presslabs+drone
    dockerfile: hack/docker/mysql-helper/Dockerfile
    context: hack/docker/mysql-helper
    tags: ["${DRONE_TAG}"]
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: tag

  publish-helm-chart:
    group: publish
    image: quay.io/presslabs/kluster-toolbox
    pull: true
    environment:
      - GH_USER=presslabs-bot
    commands:
      - cd hack/charts
      - (cd mysql-operator && helm dep build)
      - helm package mysql-operator
      - CHART="$(basename *.tgz)" ; MESSAGE="Publish $(basename $CHART .tgz)"
      - /usr/local/bin/gh put --skip-existing -m "$MESSAGE" "$CHART" "presslabs/charts/docs/"
    secrets:
      - GH_PASSWORD
    when:
      branch: master
      event: push


# end to end testing

  publish-e2e-image:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/mysql-e2e-tests
    username: presslabs+drone
    dockerfile: hack/docker/mysql-e2e-tests/Dockerfile
    context: hack/docker/mysql-e2e-tests
    tags: ["${DRONE_BRANCH}", "latest"]
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      branch: master
      event: push


  start-kubernetes:
    image: quay.io/presslabs/kluster-toolbox
    group: build
    secrets:
      - GOOGLE_CREDENTIALS
    environment:
      - CLUSTER_NAME=mysql-op-x${DRONE_BUILD_NUMBER}
      - KUBECONFIG=/go/.kube/config
      - HELM_HOME=/go/.helm/
    commands:
      - setup-credentials-helper.sh
      - gcloud container clusters create $CLUSTER_NAME
          --zone europe-west3-b --project testing-reactor
          --preemptible --cluster-version 1.10
      # initialize cluster
      - kubectl create serviceaccount -n kube-system tiller
      - kubectl create clusterrolebinding tiller-crule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
      - helm init --service-account tiller --wait
      - helm repo add presslabs https://presslabs.github.io/charts
      - helm dependency update hack/charts/mysql-operator
    when:
      # branch: master
      event: push

  e2e-tests:
    image: quay.io/presslabs/mysql-e2e-tests:latest
    environment:
      - APP_VERSION=${DRONE_TAG}
      - KUBECONFIG=/go/.kube/config
      - HELM_HOME=/go/.helm/
      - CLUSTER_NAME=mysql-op-x${DRONE_BUILD_NUMBER}
    commands:
      - go test ./test/e2e -v --kubernetes-config /go/.kube/config --kubernetes-context gke_testing-reactor_europe-west3-b_$CLUSTER_NAME
            --operator-image quay.io/presslabs/mysql-operator:${DRONE_BRANCH/master/latest}
            --helper-image quay.io/presslabs/mysql-helper:${DRONE_BRANCH/master/latest}
    when:
      # branch: master
      event: push

  stop-kubernetes:
    image: quay.io/presslabs/kluster-toolbox
    secrets:
      - GOOGLE_CREDENTIALS
    environment:
      - CLUSTER_NAME=mysql-op-x${DRONE_COMMIT_SHA:0:7}
      - KUBECONFIG=/go/.kube/config
    commands:
      - setup-credentials-helper.sh
      - gcloud container clusters delete $CLUSTER_NAME --quiet --zone europe-west3-b --project testing-reactor
     
    when:
      status: [ success, failure ]
      # branch: master
      event: push

