apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: quay.io/presslabs/mysql-operator
    docker:
      dockerfile: hack/development/Dockerfile.operator
  - image: quay.io/presslabs/mysql-operator-sidecar
    docker:
      dockerfile: hack/development/Dockerfile.sidecar
  - image: quay.io/presslabs/orchestrator
    docker:
      dockerfile: hack/development/Dockerfile.orchestrator
  local:
    push: true
deploy:
  helm:
    releases:
    - name: test
      chartPath: hack/charts/mysql-operator
      valuesFiles:
      - hack/development/dev-values.yaml
      values:
        image: quay.io/presslabs/mysql-operator
        sidecarImage: quay.io/presslabs/mysql-operator-sidecar
        orchestrator.image: quay.io/presslabs/orchestrator
