apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: mysqlusers.mysql.presslabs.org
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type == "Ready")].status
    description: The user status
    name: Ready
    type: string
  - JSONPath: .spec.clusterRef.name
    name: Cluster
    type: date
  - JSONPath: .spec.user
    name: UserName
    type: date
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: mysql.presslabs.org
  names:
    kind: MySQLUser
    plural: mysqlusers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            accountResourceLimits:
              description: 'AccountResourceLimits allow settings limit per mysql user
                as defined here: https://dev.mysql.com/doc/refman/5.7/en/user-resources.html'
              type: object
            allowedHost:
              description: AllowedHost is the allowed host to connect from. This field
                should be immutable.
              type: string
            clusterRef:
              description: ClusterRef represents a reference to the MySQL cluster.
                This field should be immutable.
              type: object
            password:
              description: Password is the password for the user.
              properties:
                key:
                  description: The key of the secret to select from.  Must be a valid
                    secret key.
                  type: string
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              required:
              - key
              type: object
            permissions:
              description: Permissions is the list of roles that user has in the specified
                database.
              items:
                properties:
                  permissions:
                    description: Permissions represents the permissions granted on
                      the schema/tables
                    items:
                      type: string
                    type: array
                  schema:
                    description: Schema represents the schema to which the permission
                      applies
                    type: string
                  tables:
                    description: Tables represents the tables inside the schema to
                      which the permission applies
                    items:
                      type: string
                    type: array
                required:
                - schema
                - tables
                - permissions
                type: object
              type: array
            user:
              description: User is the name of the user that will be created with
                will access the specified database. This field should be immutable.
              type: string
          required:
          - clusterRef
          - user
          - password
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the MySQLUser resource conditions
                list.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of MySQLUser condition.
                    type: string
                required:
                - type
                - status
                - lastTransitionTime
                - reason
                - message
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
