---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: mysqlclusters.mysql.presslabs.org
spec:
  group: mysql.presslabs.org
  names:
    kind: MysqlCluster
    plural: mysqlclusters
    shortNames:
    - mysql
    - mysql-cluster
    singular: mysqlcluster
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            MaxSlaveLatency:
              description: MaxSlaveLatency represents the allowed latency for a slave
                node in seconds. If set then the node with a latency grater than this
                is removed from service.
              format: int64
              type: integer
            backupSchedule:
              description: Specify under crontab format interval to take backups leave
                it empty to deactivate the backup process Defaults to ""
              type: string
            backupSecretName:
              type: string
            backupUri:
              type: string
            initBucketSecretName:
              type: string
            initBucketUri:
              description: A bucket URI that contains a xtrabackup to initialize the
                mysql database.
              type: string
            mysqlConf:
              description: A map[string]string that will be passed to my.cnf file.
              type: object
            mysqlVersion:
              description: Represents the percona image tag. Defaults to 5.7
              type: string
            podSpec:
              properties:
                affinity: {}
                annotations:
                  type: object
                imagePullPolicy:
                  type: string
                imagePullSecrets:
                  items: {}
                  type: array
                labels:
                  type: object
                nodeSelector:
                  type: object
                resources: {}
            replicas:
              description: The number of pods. This updates replicas filed Defaults
                to 0
              format: int32
              type: integer
            secretName:
              description: The secret name that contains connection information to
                initialize database, like USER, PASSWORD, ROOT_PASSWORD and so on
                This secret will be updated with DB_CONNECT_URL and some more configs.
                Can be specified partially Defaults is <name>-db-credentials (with
                random values)
              type: string
            volumeSpec:
              properties:
                accessModes:
                  description: 'AccessModes contains the desired access modes the
                    volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1'
                  items:
                    type: string
                  type: array
                resources: {}
                selector:
                  description: A label selector is a label query over a set of resources.
                    The result of matchLabels and matchExpressions are ANDed. An empty
                    label selector matches all objects. A null label selector matches
                    no objects.
                  properties:
                    matchExpressions:
                      description: matchExpressions is a list of label selector requirements.
                        The requirements are ANDed.
                      items:
                        description: A label selector requirement is a selector that
                          contains values, a key, and an operator that relates the
                          key and values.
                        properties:
                          key:
                            description: key is the label key that the selector applies
                              to.
                            type: string
                          operator:
                            description: operator represents a key's relationship
                              to a set of values. Valid operators are In, NotIn, Exists
                              and DoesNotExist.
                            type: string
                          values:
                            description: values is an array of string values. If the
                              operator is In or NotIn, the values array must be non-empty.
                              If the operator is Exists or DoesNotExist, the values
                              array must be empty. This array is replaced during a
                              strategic merge patch.
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                      type: array
                    matchLabels:
                      description: matchLabels is a map of {key,value} pairs. A single
                        {key,value} in the matchLabels map is equivalent to an element
                        of matchExpressions, whose key field is "key", the operator
                        is "In", and the values array contains only "value". The requirements
                        are ANDed.
                      type: object
                storageClassName:
                  description: 'Name of the StorageClass required by the claim. More
                    info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1'
                  type: string
                volumeMode:
                  description: volumeMode defines what type of volume is required
                    by the claim. Value of Filesystem is implied when not included
                    in claim spec. This is an alpha feature and may change in the
                    future.
                  type: string
                volumeName:
                  description: VolumeName is the binding reference to the PersistentVolume
                    backing this claim.
                  type: string
      required:
      - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
