---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: mysqlbackups.mysql.presslabs.org
spec:
  group: mysql.presslabs.org
  names:
    kind: MysqlBackup
    plural: mysqlbackups
    shortNames:
    - backup
    singular: mysqlbackup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            backupSecretName:
              description: BackupSecretName the name of secrets that contains the
                credentials to access the bucket. Default is used the secret specified
                in cluster. optinal
              type: string
            backupUri:
              description: BucketUri a fully specified bucket URI where to put backup.
                Default is used the one specified in cluster. optional
              type: string
            clusterName:
              description: ClustterName represents the cluster for which to take backup
              type: string
          required:
          - clusterName
      required:
      - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
