# Default values for mysql-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## The cluster number of nodes
replicas: 1

## For setting custom docker image or specifying mysql version
## the image field has priority over mysqlVersion.
# image: percona:5.7
# mysqlVersion: "5.7"

## MySQL connect credentials, those credentials will be provisioned in the cluster
rootPassword: ""
appUser: ""
appPassword: ""
appDatabase: ""
# appSecretLabels: {}
# appSecretAnnotations: {}

podSpec:
mysqlConf:
volumeSpec:

service: 
  # - name: test-prometheus
  #   labels: {}
  #   ports: 
  #     - name: prometheus
  #       port: 9125
  #       protocol: TCP
  #       targetPort: 9125
  #   selector: {}
  #   type: ClusterIP
    
serverIDOffset:

initBucketURL:
initBucketSecretName:

backupSchedule:
backupScheduleJobsHistoryLimit:
backupURL:
backupSecretName:
backupRemoteDeletePolicy:
# backupSecretLabels: {}
# backupSecretAnnotations: {}
backupCredentials:
  # AWS_ACCESS_KEY_ID: ?
  # AWS_SECRET_ACCESS_KEY: ?
  # AWS_REGION: us-east-1
  # AWS_ACL: ?

  # GCS_SERVICE_ACCOUNT_JSON_KEY: ?
  # GCS_PROJECT_ID: ?
  # GCS_OBJECT_ACL: ?
  # GCS_BUCKET_ACL: ?
  # GCS_LOCATION: ?
  # GCS_STORAGE_CLASS: MULTI_REGIONAL

  # HTTP_URL: ?

