apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}

  serviceName: {{ template "serviceName" . }}

  replicas: {{ .Values.mysql.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-mysql
        image: {{ .Values.tools.image }}
        args: ["db", "config_files"]
        env:
        {{- include "titanium.env" . | nindent 8 }}
        {{- include "titanium.env.rootPassword" . | nindent 8 }}
        volumeMounts:
        {{- include "titanium.volumeMount" . | nindent 8 }}
        # used to compute config files 
        - name: podinfo
          mountPath: /mnt/podinfo
          readOnly: false
      - name: clone-mysql
        image: {{ .Values.tools.image }}
        args: ["db", "clone"]
        env:
        {{- include "titanium.env" . | nindent 8 }}
        {{- include "titanium.env.replication" . | nindent 8 }}
        volumeMounts:
        {{- include "titanium.volumeMount" . | nindent 8 }}
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        env:
          {{- include "titanium.env.rootPassword" . | nindent 10 }}
          {{- if .Values.mysql.dbName }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql-secrets
                key: MYSQL_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql-secrets
                key: MYSQL_USER
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql-secrets
                key: MYSQL_DATABASE
          {{- end }}
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
        livenessProbe:
          exec:
            command: ["mysqladmin", "--defaults-file=/etc/mysql/client.cnf", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "--defaults-file=/etc/mysql/client.cnf", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      - name: titanium
        image: {{ .Values.tools.image }}
        ports:
        - name: xtrabackup
          containerPort: 3307
        args: ["db configure; db serve_backups"]
        env:
        {{- include "titanium.env" . | nindent 8 }}
        {{- include "titanium.env.replication" . | nindent 8 }}
        volumeMounts:
        {{- include "titanium.volumeMount" . | nindent 8 }}
        resources:
          {{ toYaml .Values.tools.resources | nindent 10 }}
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: {{ .Release.Name }}-mysql
      - name: secret-conf
        secret:
          secretName: {{ .Release.Name }}-mysql-secrets
      - name: podinfo
        downwardAPI:
          items:
            - path: mem_request
              resourceFieldRef:
                containerName: mysql
                resource: requests.memory
      {{- if .Values.persistenceDisabled }}
      - name: data
        emptyDir: {}
      {{- end }}

  volumeClaimTemplates:
{{- if not .Values.persistenceDisabled }}
  - metadata:
      name: data
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: {{ .Values.mysql.persistence.storage }}
{{- else }} []
{{- end }}
