apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: foo
spec:
  replicas: 1
  secretName: the-secret
  # mysqlVersion: 5.7
  # initBucketUri: gs://bucket_name/backup.xtrabackup.gz
  # initBucketSecretName:

  ## For recurrent backups set backupSchedule with a cronjob expression
  # backupSchedule:
  # backupUri: s3://bucket_name/
  # backupSecretName:

  ## Configs that will be added to my.cnf for cluster
  # mysqlConf:
  #   innodb-buffer-size: 128M


  ## Specify additional pod specification
  # podSpec:
  #   resources:
  #     requests:
  #       memory: 1G
  #       cpu:    200m

  ## Specify additional volume specification
  # volumeSpec:
  #   accessModes: [ "ReadWriteOnce" ]
  #   resources:
  #     requests:
  #       storage: 1Gi

  ## Specify service objectives
  ## If thoses SLO are not fulfilled by cluster node then that node is
  ## removed from scheme
  # targetSLO:
  #   maxSlaveLatency: 10s
