apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlBackup
metadata:
  name: bar-backup

spec:
  # this field is required
  clusterName: foo

  ## if backupUri is specified then the backup will be put
  ## at this path, else the backup uri will be filled with
  ## the cluster preset backupUri and a random name
  # backupUri: gs://bucket_name/path/to/backup.xtrabackup.gz

  ## specify a secret where to find credentials to access the
  ## bucket
  # backupSecretName: backup-secret
