apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
type: Opaque
data:
    # AWS_ACCESS_KEY_ID: ?
    # AWS_SECRET_KEY: ?
    # AWS_REGION: us-east-1
    # AWS_ACL: ?

    # GCS_SERVICE_ACCOUNT_JSON_KEY: ?
    # GCS_PROJECT_ID: ?
    # GCS_OBJECT_ACL: ?
    # GCS_BUCKET_ACL: ?
    # GCS_LOCATION: ?
    # GCS_STORAGE_CLASS: MULTI_REGIONAL

    # HTTP_URL: ?
    
    # AZUREBLOB_ACCOUNT: ?
    # AZUREBLOB_KEY: ?

# for more details check docker entrypoint: hack/docker/mysql-helper/docker-entrypoint.sh
