apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlBackup
metadata:
  name: my-cluster-backup

spec:
  # this field is required
  clusterName: my-cluster

  ## if backupURL is specified then the backup will be put
  ## at this path, else the backup UR will be filled with
  ## the cluster preset backupURL and a random name
  # backupURL: gs://bucket_name/path/to/backup.xtrabackup.gz

  ## specify a secret where to find credentials to access the
  ## bucket
  # backupSecretName: backup-secret
