apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 2
  secretName: my-secret
  # mysqlVersion: 5.7
  # initBucketURI: gs://bucket_name/backup.xtrabackup.gz
  # initBucketSecretName:

  ## PodDisruptionBudget
  # minAvailable: 1

  ## For recurrent backups set backupSchedule with a cronjob expression
  # backupSchedule:
  # backupURL: s3://bucket_name/
  # backupSecretName:
  # backupScheduleJobsHistoryLimit:


  ## Configs that will be added to my.cnf for cluster
  # mysqlConf:
  #   innodb-buffer-size: 128M


  ## Specify additional pod specification
  # podSpec:
  #   resources:
  #     requests:
  #       memory: 1G
  #       cpu:    200m

  ## Specify additional volume specification
  # volumeSpec:
  #   # https://godoc.org/k8s.io/api/core/v1#EmptyDirVolumeSource
  #   emptyDir: {}

  #   # https://godoc.org/k8s.io/api/core/v1#HostPathVolumeSource
  #   hostPath:
  #     path:
  #     type:

  #   # https://godoc.org/k8s.io/api/core/v1#PersistentVolumeClaimSpec
  #   persistentVolumeClaim:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi

  ## Specify service objectives
  ## If thoses SLO are not fulfilled by cluster node then that node is
  ## removed from scheme
  # targetSLO:
  #   maxSlaveLatency: 10s
