# Default values for mysql-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## The cluster number of nodes
replicas: 1

## MySQL connect credentials, those credentials will be provisioned in the cluster
rootPassword: ""
appUser: ""
appPassword: ""
appDatabase: ""

podSpec:
mysqlConf:
volumeSpec:

serverIDOffset:

backupSchedule:
backupScheduleJobsHistoryLimit:
backupURL:
backupSecretName:
backupRemoteDeletePolicy:
backupCredentials:
  # AWS_ACCESS_KEY_ID: ?
  # AWS_SECRET_ACCESS_KEY: ?
  # AWS_REGION: us-east-1
  # AWS_ACL: ?

  # GCS_SERVICE_ACCOUNT_JSON_KEY: ?
  # GCS_PROJECT_ID: ?
  # GCS_OBJECT_ACL: ?
  # GCS_BUCKET_ACL: ?
  # GCS_LOCATION: ?
  # GCS_STORAGE_CLASS: MULTI_REGIONAL

  # HTTP_URL: ?

