###############################################################################
#  Build rclone
###############################################################################
FROM debian:stretch as rclone

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gnupg ca-certificates wget unzip

COPY hack/docker/rclone.gpg /root/rclone.gpg
RUN gpg --import /root/rclone.gpg

ENV RCLONE_VERSION=1.52.3

RUN wget -nv https://github.com/ncw/rclone/releases/download/v${RCLONE_VERSION}/rclone-v${RCLONE_VERSION}-linux-amd64.zip \
    && wget -nv https://github.com/ncw/rclone/releases/download/v${RCLONE_VERSION}/SHA256SUMS \
    && gpg --verify --output=- SHA256SUMS > sums \
    && sha256sum -c --ignore-missing sums \
    && unzip rclone-*-linux-amd64.zip \
    && mv rclone-*-linux-amd64/rclone /usr/local/bin/ \
    && chmod 755 /usr/local/bin/rclone


##############################################################################
#  Docker image for sidecar containers
###############################################################################
FROM debian:stretch-slim as sidecar

RUN groupadd -g 999 mysql
RUN useradd -u 999 -r -g 999 -s /sbin/nologin \
    -c "Default Application User" mysql

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https ca-certificates wget \
    && rm -rf /var/lib/apt/lists/*

COPY hack/docker/percona.gpg /etc/apt/trusted.gpg.d/percona.gpg
RUN echo 'deb https://repo.percona.com/apt stretch main' > /etc/apt/sources.list.d/percona.list

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        percona-toolkit percona-xtrabackup-80 unzip \
    && wget https://github.com/maxbube/mydumper/releases/download/v0.9.5/mydumper_0.9.5-2.stretch_amd64.deb \
    && dpkg -i mydumper_0.9.5-2.stretch_amd64.deb \
    && rm -rf mydumper_0.9.5-2.stretch_amd64.deb /var/lib/apt/lists/* \
    && mkdir -p /usr/share/src \
    && wget https://github.com/maxbube/mydumper/archive/v0.9.5.tar.gz -O /usr/share/src/mydumper-v0.9.5.tar.gz

USER mysql

# set expiration time for dev images
# https://support.coreos.com/hc/en-us/articles/115001384693-Tag-Expiration
LABEL quay.expires-after=2d

COPY ./hack/docker/sidecar-entrypoint.sh /usr/local/bin/sidecar-entrypoint.sh
COPY ./bin/mysql-operator-sidecar_linux_amd64 /usr/local/bin/mysql-operator-sidecar

# copy rclone 
COPY --from=rclone /usr/local/bin/rclone /usr/local/bin/rclone

ENTRYPOINT ["/usr/local/bin/sidecar-entrypoint.sh"]
