{{- if not .Values.orchestrator.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql-operator.orc-secret-name" . }}
  labels:
    app: {{ template "mysql-operator.name" . }}
    chart: {{ template "mysql-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  TOPOLOGY_USER: {{ printf "%s" .Values.orchestrator.topologyUser | b64enc | quote }}
  {{- if .Values.orchestrator.topologyPassword }}
  TOPOLOGY_PASSWORD: {{ printf "%s" .Values.orchestrator.topologyPassword | b64enc | quote }}
  {{- else }}
  TOPOLOGY_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
