{{- if and .Values.podSecurityPolicy.enabled .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ template "mysql-operator.fullname" . }}'
  labels:
    app: '{{ template "mysql-operator.name" . }}'
    chart: '{{ template "mysql-operator.chart" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
roleRef:
  kind: Role
  name: '{{ template "mysql-operator.fullname" . }}'
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts:
- kind: ServiceAccount
  name: {{ template "mysql-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
