{{- if and .Values.podSecurityPolicy.enabled .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ template "mysql-operator.fullname" . }}'
  labels:
    app: '{{ template "mysql-operator.name" . }}'
    chart: '{{ template "mysql-operator.chart" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - '{{ template "mysql-operator.fullname" . }}'
{{- end }}
