baseURL = "https://www.presslabs.com/docs/mysql-operator"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true
theme = "hugo-docs-theme"
languageCode = "en-us"
title = "MySQL Operator documentation"

[markup]
  defaultMarkdownHandler = "goldmark"

[params]
  related = true
  logo_text = "DOCS"
  versions = false

[params.algolia]
  appId = "0TS6NFHDBC"
  apiKey = "b2efcfd6516eed7a2f19269f9cb13acb"
  indexName = "MySQL Operator Docs"
  vars = ["title", "description", "content", "date", "lastmod", "permalink", "text", "lvl0", "lvl1", "url"]

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "menu.global.parent"
  weight = 150

[[menu.global]]
  name = "MySQL Operator"
  weight = 1
  identifier = "mysql-operator"

[[menu.global]]
  name = "MySQL Cluster"
  weight = 2
  identifier = "mysql-cluster"

[[menu.global]]
  name = "Accessing the Orchestrator"
  weight = 3
  url = "/orchestrator"
