{{- if .Values.backupCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql-cluster.backupSecretName" . }}
  labels:
    app: {{ template "mysql-cluster.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
    {{- range $key, $value := .Values.backupCredentials }}
    {{ $key | upper }}: {{ $value | b64enc | quote }}
    {{ end }}
{{- end -}}
